//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchTrackingService.EntityDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp2
    {
        public int JSTrackingID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
    
        public virtual JSTracking JSTracking { get; set; }
    }
}
