//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchTrackingService.EntityDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobSearchTrackingEntities : DbContext
    {
        public JobSearchTrackingEntities()
            : base("name=JobSearchTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<FollowUp1> FollowUp1 { get; set; }
        public virtual DbSet<FollowUp2> FollowUp2 { get; set; }
        public virtual DbSet<JSTracking> JSTrackings { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
